version: "3"
services:
  app1:
    build: .
    command: make start
    container_name: host1.com
    environment:
      - EPMDLESS_DIST_PORT=17012
      - NODE_NAME=app1@host1.com
    ports:
      - 17012:17012
    networks:
      - net1

  app2:
    build: .
    command: make start
    container_name: host2.com
    environment:
      - EPMDLESS_DIST_PORT=17013
      - NODE_NAME=app2@host2.com
    ports:
      - 17013:17013
    networks:
      - net1

  app3:
    build: .
    command: make start
    container_name: host3.com
    environment:
      - EPMDLESS_DIST_PORT=17014
      - NODE_NAME=app3@host3.com
    ports:
      - 17014:17014
    networks:
      - net1

# We're using custom network setup, as it ships with a DNS
# system which allows containers to communicate by hostnames.
networks:
  net1:
    driver: bridge